### ISSUE TITLE
[request] Move faster in the level editor

### ISSUE THREAD

**Issue by SanskritFritz** [acmepjz/meandmyshadow#12]
From Ákos:
I often create huge maps and getting from one side to another takes considerable amount of time. I'd like to have a possibility to move much faster in the level editor.

**Comment by acmepjz** [comment]
In the level editor you can use arrow keys and shift+arrow keys to move camera. I added some code to make shift+arrow keys move the camera faster. Can you try it?

**Comment by SanskritFritz** [comment]
I tried the latest code, but don't see any significant difference.

**Comment by SanskritFritz** [comment]
oops. missed the RIGHT shift part :smile: 
Yes, this is much better, appreciated! Thanks!
