### ISSUE TITLE
Moving blocks don't work in Level Editor?

### ISSUE THREAD

**Issue by bgalon2000** [acmepjz/meandmyshadow#14]
I have just installed the nightly build and went into the level editor. I placed a moving block and clicked play - but could not move it with either me or my shadow. Am I doing something wrong?

bgalon_2000

**Comment by acmepjz** [comment]
I think you mean _pushable block_. The moving block is a block which moves according to a predefined path.

**Comment by bgalon2000** [comment]
Yes. I went to sleep last night and as I was falling asleep I realised I'm talking nonsense but was too tired to stand up log back into my laptop...

It's been too long... Are pushable blocks implemented already in the editor?

**Comment by bgalon2000** [comment]
Checked it now - looks alright. Closing issue.
