### ISSUE TITLE
Port to SDL 2.*

### ISSUE THREAD

**Issue by oyvindln** [acmepjz/meandmyshadow#2]
This would provide a [number of improvements](https://wiki.libsdl.org/MigrationGuide), including automatic hardware acceleration.

**Comment by acmepjz** [comment]
It's a good idea to port to SDL2, but it will take some time. I have a game using SDL2, but I use the OpenGL calls explicitly; I'm not familiar with SDL2 graphics functions now.

**Comment by oyvindln** [comment]
This is rather old news, but I just want to note that I started on this, it does run on SDL2 but there are a bunch of issues that needs to be fixed on the port before it's usable. Maybe I'll get around to it at some point, but it's up [here](https://github.com/oyvindln/meandmyshadow) if anyone else is interested in playing with it.

**Comment by oyvindln** [comment]
So I've started tinkering with this again. I'm working on moving to using the new SDL_Texture type for rendering as it works in hardware by default.

I'm wondering if it's okay to start requiring a C++11 conformant compiler for this version as it would make the code a bit cleaner, and would make it possible to use the newest version of tinygettext.

**Comment by acmepjz** [comment]
I think it is OK to use some C++11 features.


As for the SDL_Texture, I think there are some more codes which need to be changed, for example the call to SDL_gfx functions, which should be changed to SDL2 built-in primitive drawing functions.


Also, if an SDL_Texture is created to be a render target, then its content will be lost when the window resizes (at least on some version of Windows), so maybe some code is needed to handle this or if you decided that such minor glitches are negligible.

**Comment by oyvindln** [comment]
So I'm mostly done with this now, only thing still missing is some joystick stuff that got changed in SDL2 and some minor bugs. Will make a PR from [my repo](https://github.com/oyvindln/meandmyshadow) soon.

**Comment by oyvindln** [comment]
Soon heh
Still have some bugs to fix before a PR.

See https://forum.freegamedev.net/viewtopic.php?f=48&t=7875
