### ISSUE TITLE
"Custom Levels" levelpack name is in English

### ISSUE THREAD

**Issue by gunchleoc** [acmepjz/meandmyshadow#25]
In the editor, "Custom Levels" is displayed in English. We need to be careful when fixing this, because this name also used in the program logic.

**Comment by gunchleoc** [comment]
I just tested this and it's still displayed in English, although the string is on Transifex now.

**Comment by acmepjz** [comment]
I have not update the translations in the git master branch yet, except for zh_CN translation. Can you download the po file from Transifex for replacement and try again?

**Comment by gunchleoc** [comment]
I did that already before reporting ;)

**Comment by acmepjz** [comment]
I'm sorry to hear that, but I can't reproduce this bug:

![screenshot](https://user-images.githubusercontent.com/3397779/45217517-f4867c80-b2d6-11e8-9aa1-74d86cd4d819.JPG)

I'm using the commit fe8925d. I'm afraid that you need to find out the bug by yourself ☹️ try set a breakpoint on corresponding code.

**Comment by acmepjz** [comment]
@gunchleoc , can you check if this is fixed in the V0.5 released version?

**Comment by gunchleoc** [comment]
Yep, I see it translated :)
