### ISSUE TITLE
Levelpacks po files still point to transifex

### ISSUE THREAD

**Issue by eugeneloza** [acmepjz/meandmyshadow#26]
Levelpacks po files headers still point to transifex, e.g.
`"Language-Team: Russian (https://www.transifex.com/acmepjz/teams/88148/ru/)\n"`
I believe they need to be updated to weblate.

**Comment by acmepjz** [comment]
This will be auto updated if you make any changes through Weblate. Or you can modify it manually?

**Comment by eugeneloza** [comment]
Sure, I can modify it manually (just copy the Weblate stamp from "global" translation seems ok), however, I guess that Weblate might have its own opinion on how the header should look like.

**Comment by mesnevi** [comment]
@eugeneloza sorry for irrelevant commenting, I've failed to find a way to contact you directly. Is there any way I can help with Russian translation? Is there any IRC channel you guys discuss things? Or do you use emails? Or simply comment on issues?

**Comment by eugeneloza** [comment]
@mesnevi, hi!
My email is Zh____Loza____(ear)_gmail.com (remove underslashes). Was just the same way surprised that there is no way to send a direct mail through github. I've also written you a message to the email you've signed off at pull request.

**Comment by eugeneloza** [comment]
Seems like this was fixed by Weblate. Closing.
