### ISSUE TITLE
Error: "The game data file could not be found"

### ISSUE THREAD

**Issue by SanskritFritz** [acmepjz/meandmyshadow#31]
I installed the stable 0.5 version this way:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make
make install DESTDIR=${pkgdir}

```
When starting the binary from the install dir I receive a popup message as the subject says. The terminal writes:
```
frank@HomeC ~/B/a/S/m/p/m/u/bin> ./meandmyshadow 
User preferences will be fetched from: /home/frank/.config/meandmyshadow/
User data will be fetched from: /home/frank/.local/share/meandmyshadow/
trying: /meandmyshadow/data/
FATAL ERROR: Failed to configure paths.
```
However starting the same binary from where it was compiled works.

**Comment by acmepjz** [comment]
Maybe it's related to https://github.com/acmepjz/meandmyshadow/pull/29. Can you try the latest code in git master branch?

**Comment by SanskritFritz** [comment]
I forgot to mention that git head works flawlessly.

**Comment by acmepjz** [comment]
I'm glad to hear that. I'll make a bug fix release a few days later.

**Comment by SanskritFritz** [comment]
The new version works perfectly!
