### ISSUE TITLE
keybindings are hardcoded in Tutorial levelpack translation

### ISSUE THREAD

**Issue by eugeneloza** [acmepjz/meandmyshadow#32]
e.g.

> Restart the game by pressing the 'R' key.

> Go back to the previous checkpoint by pressing F3.

> Press space to record your moves.

> you don't have to press the down key, it will activate when you walk in it.

As far as I see, those keys may be reassigned in Options.

Compare to

> Press %s key to save the game.

> Press %s key to swap the position of player and shadow.

> Press %s key to activate the switch.

> Press %s key to teleport.

> Press %s to restart current level or press %s to load the game.

in locale.

**Comment by acmepjz** [comment]
OK, I'll fix it in next version.

**Comment by eugeneloza** [comment]
I might suggest a simple way to, by providing "macros" e.g. by processing each levelpack locale string with "string replace". I'm very bad at C++, but I guess this approach should work: https://stackoverflow.com/questions/3418231/replace-part-of-a-string-with-another-string

This will allow not only use such things in Tutorial, but will enable level creators to use those too and will not need to have something hardcoded exclusively for Tutorial maps. E.g. macro "%swapkey" will be replaced to "spacebar", "%loadkey" to "F3", "%restartkey" to "R", etc.

**Comment by acmepjz** [comment]
Yes, this is also my plan.

**Comment by acmepjz** [comment]
already fixed in V0.5.1 Development version
