### ISSUE TITLE
Teleporter or Portal?

### ISSUE THREAD

**Issue by eugeneloza** [acmepjz/meandmyshadow#34]
In Tutorial the teleporters are called portals... Which one is more consistent?

**Comment by acmepjz** [comment]
I don't know 😑 I think portal is OK. It is called teleporter only in level editor.

**Comment by acmepjz** [comment]
OK, I decided to rename all "teleporter" in the translatable string to "portal". It is still called "teleporter" in some part of code and in the level file format, though.
