### ISSUE TITLE
Strange letter error in key

### ISSUE THREAD

**Issue by eugeneloza** [acmepjz/meandmyshadow#35]
For some reason in Russian language it puts "ВнШз" instead of "Вниз". It happens only in this key, other uses of "и" letter are fine. I've tripple-checked, the word is written correctly in PO files.

(UPD) Same problem in Ukrainian translation.

![mms_wrongletter](https://user-images.githubusercontent.com/10726162/47672470-c167b780-dbba-11e8-9413-0d3a09e559b3.png)

**Comment by acmepjz** [comment]
This is because the game tries to make the key name in ALL CAPS. However, the code only works well for Latin characters.

I have two possible solutions:

1. Remove this code completely, but this will make keys 'a'-'z' appear in lower case, which is ugly IMHO.
2. Modify the make-upper code to only modify characters 'a'-'z'; this will make characters with accents unchanged but other characters changed in a word (this will most likely happen in French, German, etc.).

I think now we need some discussion, and once the solution is determined I'll fix the code ASAP.

**Comment by eugeneloza** [comment]
In this case I have a third solution :D

Replace Russian/Ukrainian "и" letter with visually very similar Greek letter "ͷ":
```
msgctxt "keys"
msgid "Down"
msgstr "Внͷз"
```
It's absolutely wrong from translator's point of view, but looks exactly the same in the font Me and My Shadow currently uses. So, feels like a good solution :)

![untitled](https://user-images.githubusercontent.com/10726162/47713418-e6077200-dc42-11e8-8e4a-874594589ba7.png)

If that's ok, then I'll just push this commit and we're done here for now. Unless this bug appears for other letters. At the moment only very few letters of Cyrillic UTF8 range are affected (of Russian/Ukrainian letters it seems like only "и" is going mad).

**Comment by eugeneloza** [comment]
On the other hand:

> but this will make keys 'a'-'z' appear in lower case, which is ugly IMHO

I guess this can be fixed straight in translation files (i.e. write "DOWN" instead of "Down" and capitalize it by code). No need for additional buggy code to capitalize letters, keynames won't be ever used uncapitalized, I believe.

**Comment by acmepjz** [comment]
> In this case I have a third solution :D
>
> Replace Russian/Ukrainian "и" letter with visually very similar Greek letter "ͷ":

Don't worry, I'll commit an ad-hoc fix soon so you don't need to use the Greek letter to substitute. And I plan to release a bug fix release V0.5a soon.

**Comment by acmepjz** [comment]
Strange, on my computer it shows "Вниз" instead of "ВнШз". Anyway I'll commit the ad-hoc fix and can you check if it will fix the problem.

I think I should keep this issue open unless the proper fix (which will be in V0.6) is committed.

**Comment by eugeneloza** [comment]
> Don't worry

It's just 30-50 seconds to do :) So, no problem, thou a good fix would be better (if it's needed).

>  on my computer

Which OS do you have? I'm experiencing this under Win7x64.

**Comment by acmepjz** [comment]
I think this is (temporarily) fixed in the latest nightly build. Can you check it?

> Which OS do you have? I'm experiencing this under Win7x64.

Win10 x64 with zh_CN locale. I'm afraid that this depends on the system default locale.

**Comment by eugeneloza** [comment]
Works perfectly!
