### ISSUE TITLE
Add-on descriptions have ugly horizontal scrollbar

### ISSUE THREAD

**Issue by Wuzzy2** [acmepjz/meandmyshadow#45]
If you open the add-on description in the add-ons menu, there is almost always an ugly horizontal scrollbar. This is almost always caused by long URLs in the text.

Possible ways to fix this:
- Make the text area bigger
- Move the URLs that are automatically added (i.e. license URL) out of the description text box

Version: 0.5.1 Alpha

**Comment by Wuzzy2** [comment]
I had just an idea how to fix the long URLs:
Just don't write the full URL text at all, instead, make clickable text. Like in the web. For example, make the text of the license name clickable and hide the link behind the click.

**Comment by acmepjz** [comment]
I think it's a good idea to replace long URLs with "...". Will be investigated later.
