### ISSUE TITLE
Pullable borders in map-editor.

### ISSUE THREAD

**Issue by pampogokiraly** [acmepjz/meandmyshadow#49]
**Hello!**
I've been working on a new map-pack, and i often found that i want to hide blocks behind the border.
It is very inconvenient, to change it from outside the map-editor so i tought to myself: Why not to be able to pull the border in and out with the *selection-tool*?

So here is how i imagine it working:
First there should be a setting that disables the auto border grow.
And the *selection-tool* should be able to pull the border like how it does with every block.

Thank you in advance! :D

**Comment by acmepjz** [comment]
Hi,

Unfortunately, if i remembered correctly, there was a design philosophy that you shouldn't put blocks outside of the border. This is also the reason why the border will expand automatically when you put blocks outside of it. Also note that the game window can be resized, so the player may found block you want to hide after window maximized.

Currently there are two workarounds:

1. add a foreground scenery layer and add some scenery blocks covering the blocks you want to hide.

2. if you are using latest nightly builds of the game and are working on maps for newest versions of game, you may use script to change the level size: add the 'onCreate' script to the level as something like:
~~~lua
local x,y,w,h=level.getRect()
level.setRect(x+50,y+50,w-50,h-50)
~~~

Anyway it's a good idea that selection-tool should be able to pull the border if there are no blocks, and I'll look at it later. 😉

**Comment by pampogokiraly** [comment]
>     2. if you are using latest nightly builds of the game and are working on maps for newest versions of game, you may use script to change the level size: add the 'onCreate' script to the level as something like:
> 
> 
> ```lua
> local x,y,w,h=level.getRect()
> level.setRect(x+50,y+50,w-50,h-50)
> ```

This is useful, thank you again :D
