### ISSUE TITLE
[request] "mass selection" in map-editor.

### ISSUE THREAD

**Issue by pampogokiraly** [acmepjz/meandmyshadow#50]
**Hello again!**
I'm back with a new *"issue"* again.
When I'm working on a map, i sometimes just construct it in the *"air"*, and then move it down to it's place.
The problem here, is that it takes too much time to select each block one by one.
My solution is to bring back (if i remeber it correctly, there was this feature...) the *"rectangle"* selection to the *selection-tool*. Not that it would be just useful but it would also bring some more uses to the *selection-tool*
It would help me a lot to just get my tool, select the area, and bring it into it's place

Thank you again in advance :P

**Comment by acmepjz** [comment]
Sounds reasonable, I'll look at it later 😄

**Comment by pampogokiraly** [comment]
That's cool! Thank you :)

**Comment by acmepjz** [comment]
Implemented in latest git version.
