### ISSUE TITLE
[texture bug] Moving Shadow Spike is one pixel off.

### ISSUE THREAD

**Issue by pampogokiraly** [acmepjz/meandmyshadow#53]
If you get your map-editor and look between the the Moving Spike and the Moving Shadow Spike with your mouse wheel, then you will notice that the Moving Shadow Spike is one pixel off from all other spikes (including normal ones).
If you need, then i might me able to fix this later, but yet i don't know if this is a feature or a texture bug.

**Comment by acmepjz** [comment]
Oops, that must be a graphical bug! The game logic is not affected. I'll fix it immediately (for the Cloudscape theme; it's possible that other themes still have this problem).
