### ISSUE TITLE
Game crashes with lua version mismatch

### ISSUE THREAD

**Issue by SanskritFritz** [acmepjz/meandmyshadow#6]
I have compiled the git head on Archlinux this way:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=meandmyshadow-git
It builds fine, however when I run the game the moment I enter a maze, the game crashes with this error:
```
frank@HomeC ~> meandmyshadow 
User preferences will be fetched from: /home/frank/.config/meandmyshadow/
User data will be fetched from: /home/frank/.local/share/meandmyshadow/
trying: /usr/share/meandmyshadow/data/
Data files will be fetched from: /usr/share/meandmyshadow/data/
Locale isn't set by user: en
PANIC: unprotected error in call to Lua API (version mismatch: app. needs 503, Lua core provides 502)
fish: “meandmyshadow” terminated by signal SIGABRT (Abort)
```
I have three versions of Lua installed (5.3, 5.2, 5.1):
```
frank@HomeC ~> locate --regex 'lua\.h$'
/usr/include/lua.h
/usr/include/lua5.1/lua.h
/usr/include/lua5.2/lua.h
```
It looks to me, the game needs Lua 5.3 but if only finds Lua 5.2. Am I missing something?

**Comment by acmepjz** [comment]
I'm not sure. The game only requires lua >=5.2. I use lua 5.2 and works under Windows. Another contributor uses lua 5.3 and it also works.

Maybe you should try to debug it? Or you can try to modify CMakeLists.txt
~~~
Find_Package (Lua REQUIRED)
~~~
to
~~~
Find_Package (Lua 5.2 EXACT REQUIRED)
~~~
to force lua5.2 (or you can try force lua5.3).

**Comment by SanskritFritz** [comment]
That didn't help sadly. The original meandmyshadow 0.4.1 version builds and runs fine here on linux. What can be the difference?

**Comment by SanskritFritz** [comment]
Hmm, sorry I answered too fast. Forcing Lua 5.2 works, the game starts and works EXCEPT the cursor keys! All other keys like R, Space or Esc work, but the cursor keys, so I cannot move in the game.

**Comment by acmepjz** [comment]
The cursor key problem is not related to this bug; in fact the SDL2 keycode is not compatible with SDL1.2 keycode, so if you use 0.4.1 before and set the key binding then it won't work under 0.5, vice versa. Maybe I should rename the config file in 0.5?

**Comment by acmepjz** [comment]
By the way, does it work if forcing lua 5.3 instead?

**Comment by acmepjz** [comment]
Another comment: the 0.4.1 doesn't have script support so it doesn't need lua at all.

**Comment by SanskritFritz** [comment]
Forcing Lua 5.3 gives the same warning and crash.
The keyboard problem was solved be simply redefining the keys in the config :smile: 
Thanks for your help, the game now works on my linux box, allowing Ákos to work further on his levels :smile:

**Comment by acmepjz** [comment]
Interestingly, on my computer forcing lua5.3 is OK.

Searching on the internet it's said that the FindLua in CMake has bugs: https://stackoverflow.com/questions/34704331 which sometimes can't find correct version of library files. Can you check the CMake output when forcing lua5.3 to see if it's the same bug as in the above link?

**Comment by SanskritFritz** [comment]
I have searched in CMakeOutput.log but it doesn't even mention Lua. So I don't know if I was looking at the right place.

**Comment by SanskritFritz** [comment]
meandmyshadow builds and runs perfectly on my Archlinux now with both Lua 5.2 and 5.3 installed. I close this ticket.
