### ISSUE TITLE
Strange death in the game when switching is activated on a moving block

### ISSUE THREAD

**Issue by SanskritFritz** [acmepjz/meandmyshadow#7]
To reproduce this we have to install the excellent level pack CastleRescue by Edward Lii (I reckon he was the original author of Me and my Shadow?). Unlock level 7. (The Second Tower). Bring your shadow to the switch. Now jump onto the upward moving block, wait until you're near the downward moving shadow block and then quicky press **up**, **space**, **down**, **space** to jump, record, switch and end recording. The result is (not always) that my shadow correctly stands on the shadow block but the white man dies unexpectedly.

**Comment by acmepjz** [comment]
I have reproduced this bug. Can you check that if 0.4.1 also has this bug?

**Comment by SanskritFritz** [comment]
I have checked it with 0.4.1 and the scenario works well there.

**Comment by acmepjz** [comment]
OK, I have checked the 0.4.1 code and since then the game logic code changed substantially. So I only came up with a suboptimal solution which changed the move logic a bit. Please check if this fixed the bug and without introducing new bugs.

**Comment by SanskritFritz** [comment]
The bug is gone now, I was able to solve the level this way, thanks. So far I haven't encountered any new problems in the game.
