### ISSUE TITLE
[question] In the level editor, how do I set delayed start for a MovingBlock?

### ISSUE THREAD

**Issue by SanskritFritz** [acmepjz/meandmyshadow#8]
I found that in the file the parameter ```t0``` is responsible for that.
For example:
```
tile(MovingBlock,200,200,50,50){
	MovingPosCount=2
	activated=1
	disable=0
	id=0
	loop=0
	t0=40
	t1=30
	x0=0
	x1=300
	y0=0
	y1=0
}
```

**Comment by acmepjz** [comment]
Currently I think it's no way to do that in level editor. 😅 Later I'll add this feature.

**Comment by SanskritFritz** [comment]
Fair enough, thanks!

**Comment by acmepjz** [comment]
I have just implemented this feature, could you have a try?

**Comment by SanskritFritz** [comment]
It works well, thank you!
One small gripe though: after I use the wheel to set the pause time I have to click on the node again otherwise the changes will not be committed even though the counter seems to indicate so.

**Comment by acmepjz** [comment]
Yes, it's intended. The counter means the pause time *about to be added*, the pause time is not actually added to the path unless you click it the node again.

**Comment by SanskritFritz** [comment]
Yeah, I get it. It just took me a while until I figured it out :smile:
